In [24]:
# import warnings
# warnings.filterwarnings('ignore')  # "error", "ignore", "always", "default", "module" or "once"
import numpy as np
import math
import pandas as pd
import matplotlib
%matplotlib inline
import sys
import os
import glob
import re

# janelas = [2,3,4,5]
janelas = [3]

# estat_modelos = pd.DataFrame (columns=['algUtl','permutacao','modelo','media','desvio'])
estat_modelos = pd.DataFrame (columns=['algUtl','permutacao', 'media-LR', 'desvio-LR', 'media-KNN', 'desvio-KNN', 'media-DTC', 'desvio-DTC', 'media-SVM', 'desvio-SVM', 'media-RFC', 'desvio-RFC'])
# estat_modelos = pd.DataFrame (columns=['algUtl','permutacao', 'lista'])
dirEst = "../csv/"

for k in janelas:

    abordagemAA = '2 - AA[dg-arj]' #'2 - AA[pet-chr]' ou '2 - AA[dg-arj]'
    dirOrig = "../csv/conjuntosDS/treinoTeste-k"+str(k)+"/"
    # dirOrig = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/conjuntosDS/treinoTeste/"
    # dirOrig = "../arqResult/csv/conjuntosDS/conjuntosDiverg/treinoTeste/"
    # estat = "../csv/estatisticaInicialDS2.csv"
    estat = "../csv/estatisticaInicialDS2-DgArj-k"+str(k)+".csv"
    # estat = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/estatisticaInicialDS2.csv"
    # estat = "../arqResult/csv/estatisticaInicialDS2.csv"

    print(dirOrig)
    
    etapa = '3 - clasf'

    # estatisticas = pd.read_csv(estat, index_col=['etapa','permutacao'], sep=';')
    estatisticas = pd.read_csv(estat, index_col=['algoritmosUtilizados','permutacao','etapa'], sep=';')
#     estatisticas.tail()

    arquivos = os.listdir(dirOrig)
    # print(arquivos)
    #print(len(arquivos))

    train = []
    test = []

    for arq in arquivos:
        if arq.startswith("train"):
            train.append(arq)
        elif arq.startswith("test"):
            test.append(arq)

    # print('tamanho de train: %d' %(len(train)))        

    # print('tamanho de test: %d' %(len(test)))

    # print (train)    
    # print (test)    



    #lista = ['10', '15', '20', '25'] #Assumindo que serão esses os conjuntos de algoritmos
    lista = ['10', '15', '20'] #Assumindo que serão esses os conjuntos de algoritmos
#     lista = ['10'] #Assumindo que serão esses os conjuntos de algoritmos
    # lista = ['3'] #Assumindo que serão esses os conjuntos de algoritmos

    for i in lista: 

        cont = 0

        trainAtual = []
        testAtual = []

        for arq in train:
            if '('+i+')' in arq:
#             if '('+i+')'+'20' in arq:
#             if ('train(10)20' in arq) | ('train(15)20' in arq) | ('train(20)20' in arq):    
                trainAtual.append(arq)
        for arq in test:
            if '('+i+')' in arq:
#             if '('+i+')'+'20' in arq:
#             if ('test(10)20' in arq) | ('test(15)20' in arq) | ('test(20)20' in arq):
                testAtual.append(arq)

    #     print('lista desordenada')
    #     print(trainAtual)

    #     print('tamanho antes: %d' %(len(trainAtual)))

        #Ordenando a lista
        trainAtual = sorted(trainAtual)
        testAtual = sorted(testAtual)

    #     for x in trainAtual:
    #         print(x)



    # #     print('lista ordenada')
    # #     print(trainAtual)

    #     print('tamanho depois: %d' %(len(trainAtual)))

    #     print(type(trainAtual))


        print (i)

    #     print(trainAtual)
    #     print(testAtual)

        tam = len(trainAtual) #Mesma coisa para testAtual

        for pos in range(tam):
    #         print(pos)
            print('')
            print('##########################')
            print('Arquivos atuais: %s e %s' %(trainAtual[pos], testAtual[pos]))
            print('##########################')

            treino = dirOrig+trainAtual[pos]
            teste = dirOrig+testAtual[pos]

    #         print('treino: %s' %(treino))

    #         tp, fp, tn, fn = 0

            num = trainAtual[pos].replace('train('+i+')','')
            num = num.replace('.csv','')

            cont += 1

            print('Iteração: %d' %(cont))

    #         print('num: %s' %(num))

            algUtl = re.sub('train.*\(', r'', trainAtual[pos]) #Alterar para fazer a substituição de tudo em uma linha só
            algUtl = re.sub('\).*', r'', algUtl) #Alterar para fazer a substituição de tudo em uma linha só
            algUtl = int(algUtl)


            print('algUtl: %d' %(algUtl))

#             permutacao = int(num)
    #         linhaAtual = estatisticas.loc[('2 - AA[pet-chr]', permutacao), : ] #Armazena a linha correspondente à permutação
    #         linhaAtual = estatisticas.loc[('1 - acm diverg', permutacao), : ] #Armazena a linha correspondente à permutação
#             linhaAtual = estatisticas.loc[algUtl, permutacao, abordagemAA, : ] #Armazena a linha correspondente à permutação
#             print (linhaAtual)
#             print(linhaAtual.columns)

        #'''
    #         all = pd.read_csv("train.csv", index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)
    #         toClass = pd.read_csv("test.csv", index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)

    #         all = pd.read_csv(treino, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)
    #         toClass = pd.read_csv(teste, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)

            all = pd.read_csv(treino, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'track10', 'track11', 'duplicata'), header = 0) #Era header = None
            toClass = pd.read_csv(teste, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'track10', 'track11', 'duplicata'), header = 0) #Era header = None


            # all['artist-title'] = all['artist'] * all['title']
            # cols = list(all.columns.values)
            # cols.pop(cols.index('duplicata'))
            # all = all[cols+['duplicata']]

            #Pesos baseados no Alg17

            all['artist-title'] = all['artist'] * all['title']
            all['soma-pesos'] = (all['artist']*1 + all['title']*2 + all['track01']*0.8 + all['track02']*0.8)/4.6
            cols = list(all.columns.values)
            cols.pop(cols.index('duplicata'))
            all = all[cols+['duplicata']]

            # toClass['artist-title'] = toClass['artist'] * toClass['title']
            # cols = list(toClass.columns.values)
            # cols.pop(cols.index('duplicata'))
            # toClass = toClass[cols+['duplicata']]

            #Pesos baseados no Alg17

            toClass['artist-title'] = toClass['artist'] * toClass['title']
            toClass['soma-pesos'] = (toClass['artist']*1 + toClass['title']*2 + toClass['track01']*0.8 + toClass['track02']*0.8)/4.6
            cols = list(toClass.columns.values)
            cols.pop(cols.index('duplicata'))
            toClass = toClass[cols+['duplicata']]

            #Separação do conjunto X do conjunto y
            # X = all.loc[:,'title':'artist-title']
            X = all.loc[:,'title':'soma-pesos']
            y = all.duplicata

            # XtoClass = toClass.loc[:,'title':'artist-title']
            XtoClass = toClass.loc[:,'title':'soma-pesos']
            ytoClass = toClass.duplicata

            from sklearn import model_selection

            X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.20, random_state=2)

            from sklearn.ensemble import RandomForestClassifier
            from sklearn.model_selection import StratifiedKFold
            from sklearn.model_selection import KFold
            from sklearn import model_selection

            seed = 500

            from sklearn.linear_model import LogisticRegression
            from sklearn.tree import DecisionTreeClassifier
            from sklearn.neighbors import KNeighborsClassifier
            from sklearn.svm import SVC

            modelos = []
            modelos.append(('LR', LogisticRegression()))
            modelos.append(('KNN', KNeighborsClassifier()))
            modelos.append(('DTC', DecisionTreeClassifier()))
            modelos.append(('SVM', SVC()))
            modelos.append(('RFC', RandomForestClassifier()))



            # Avaliação de cada modelo por vez
            resultados = []
            nomes = []
            lista = []
            for nome, modelo in modelos:
                media = 0
                desvio = 0
                
                try:
                    kfold = StratifiedKFold(n_splits=10, random_state=seed) #Mudar para n-fold
                    cv_results = model_selection.cross_val_score(modelo, X_train, y_train, cv=kfold, scoring='f1')
                    media = cv_results.mean()
                    desvio = cv_results.std()
                    msg = "%s: %f (%f)" % (nome, media, desvio) #Iprimir em um arquivo
                    print(msg)
                except ValueError:
                    media = 0
                    desvio = 0
                    print('ERRO com {0}!'.format(nome))
                    nome = nome + ' - ERRO!'
#                     break
                except:
                    media = 0.0
                    desvio = 0
                    
                
#                 lista = lista + str(media) + ';' + str(desvio) + ';'
                lista.append(media)
                lista.append(desvio)
            print(lista)   
#                 estat_modelos.loc[len(estat_modelos.index)] = [algUtl, num, nome, media, desvio]
            estat_modelos.loc[len(estat_modelos.index)] = [algUtl, num, lista[0], lista[1], lista[2], lista[3], lista[4], lista[5], lista[6], lista[7], lista[8], lista[9]]
                
#             estat_modelos.to_csv(dirEst+'estatisticasModelos.csv', sep=';', index=False)   
    estat_modelos.to_csv(dirEst+'estatisticasModelos.csv', sep=';', index=False)   

../csv/conjuntosDS/treinoTeste-k3/
10

##########################
Arquivos atuais: train(10)10.csv e test(10)10.csv
##########################
Iteração: 1
algUtl: 10
LR: 0.806667 (0.138082)
KNN: 0.920000 (0.097980)
DTC: 0.856667 (0.166032)
SVM: 0.806667 (0.138082)
RFC: 0.860000 (0.195959)
[0.80666666666666664, 0.13808210118138653, 0.92000000000000015, 0.0979795897113271, 0.85666666666666669, 0.16603212540549694, 0.80666666666666664, 0.13808210118138653, 0.85999999999999999, 0.19595917942265426]

##########################
Arquivos atuais: train(10)11.csv e test(10)11.csv
##########################
Iteração: 2
algUtl: 10
LR: 0.566667 (0.300000)
KNN: 0.550000 (0.394757)
DTC: 0.550000 (0.394757)
SVM: 0.316667 (0.320156)


C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: Undefined

RFC: 0.433333 (0.448454)
[0.56666666666666665, 0.29999999999999999, 0.55000000000000004, 0.39475730941090037, 0.55000000000000004, 0.39475730941090037, 0.3166666666666666, 0.32015621187164245, 0.43333333333333329, 0.448454134902457]

##########################
Arquivos atuais: train(10)12.csv e test(10)12.csv
##########################
Iteração: 3
algUtl: 10
LR: 0.870000 (0.107703)
KNN: 0.881667 (0.123929)
DTC: 0.863333 (0.141578)
SVM: 0.861667 (0.119269)
RFC: 0.825714 (0.130379)
[0.86999999999999988, 0.1077032961426901, 0.8816666666666666, 0.12392874296680871, 0.86333333333333329, 0.14157840387730206, 0.86166666666666669, 0.11926860441876563, 0.82571428571428562, 0.13037883055075436]

##########################
Arquivos atuais: train(10)13.csv e test(10)13.csv
##########################
Iteração: 4
algUtl: 10
LR: 0.820000 (0.130128)
KNN: 0.763333 (0.198018)
DTC: 0.863333 (0.180401)
SVM: 0.773333 (0.127192)
RFC: 0.766667 (0.200000)
[0.81999999999999995, 0.13012814197295425, 0.763333333

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: Undefined

RFC: 0.680000 (0.367333)
[0.69999999999999996, 0.37859388972001823, 0.69999999999999996, 0.37859388972001823, 0.64666666666666672, 0.35156791662493891, 0.69999999999999996, 0.37859388972001823, 0.68000000000000005, 0.36733272837215764]

##########################
Arquivos atuais: train(10)18.csv e test(10)18.csv
##########################
Iteração: 9
algUtl: 10
ERRO com LR!
KNN: 0.980000 (0.060000)
DTC: 0.946667 (0.110755)
ERRO com SVM!
RFC: 0.980000 (0.060000)
[0, 0, 0.98000000000000009, 0.059999999999999991, 0.94666666666666666, 0.11075498483890765, 0, 0, 0.98000000000000009, 0.059999999999999991]

##########################
Arquivos atuais: train(10)19.csv e test(10)19.csv
##########################
Iteração: 10
algUtl: 10
LR: 0.924242 (0.049946)
KNN: 0.926227 (0.083367)
DTC: 0.934798 (0.089776)
SVM: 0.946429 (0.086381)
RFC: 0.935317 (0.085921)
[0.9242424242424242, 0.04994640531343883, 0.92622655122655129, 0.083367410247403378, 0.93479797979797985, 0.089775891773914707, 0.9464285714

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


RFC: 0.640000 (0.340196)
[0.87333333333333341, 0.13482498944104454, 0.87333333333333341, 0.13482498944104454, 0.69999999999999996, 0.29552213679068667, 0.87333333333333341, 0.13482498944104454, 0.64000000000000001, 0.34019602192461529]
15

##########################
Arquivos atuais: train(15)10.csv e test(15)10.csv
##########################
Iteração: 1
algUtl: 15
LR: 0.873333 (0.134825)
KNN: 0.906667 (0.120000)
DTC: 0.880000 (0.151438)
SVM: 0.926667 (0.117189)
RFC: 0.846667 (0.157903)
[0.87333333333333329, 0.13482498944104457, 0.90666666666666662, 0.12, 0.87999999999999989, 0.15143755588800731, 0.92666666666666653, 0.1171893055416463, 0.84666666666666668, 0.15790292376436016]

##########################
Arquivos atuais: train(15)11.csv e test(15)11.csv
##########################
Iteração: 2
algUtl: 15
LR: 0.884762 (0.130476)
KNN: 0.931429 (0.085905)
DTC: 0.892381 (0.116491)
SVM: 0.901429 (0.152857)
RFC: 0.932381 (0.112159)
[0.88476190476190486, 0.1304761904761905, 0.93142857142857127,

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


RFC: 0.830476 (0.218749)
[0.84571428571428553, 0.16604236816912391, 0.8990476190476191, 0.13443085705595345, 0.74761904761904774, 0.21274578955893977, 0.81904761904761902, 0.30252152712892555, 0.83047619047619037, 0.21874927923431628]

##########################
Arquivos atuais: train(15)19.csv e test(15)19.csv
##########################
Iteração: 10
algUtl: 15
LR: 0.941270 (0.059413)
KNN: 0.952381 (0.058966)
DTC: 0.857540 (0.085561)
SVM: 0.952381 (0.058966)
RFC: 0.941667 (0.118145)
[0.94126984126984126, 0.059412594514961573, 0.95238095238095233, 0.058965636892084776, 0.85753968253968238, 0.085560745785966286, 0.95238095238095233, 0.058965636892084776, 0.94166666666666665, 0.11814539065631523]

##########################
Arquivos atuais: train(15)20.csv e test(15)20.csv
##########################
Iteração: 11
algUtl: 15
LR: 0.880000 (0.151438)
KNN: 0.900000 (0.152753)
DTC: 0.880000 (0.151438)
SVM: 0.900000 (0.152753)
RFC: 0.913333 (0.136789)
[0.87999999999999989, 0.15143755588800731, 0

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


RFC: 0.866667 (0.305505)
[0.94000000000000006, 0.091651513899116785, 0.95999999999999996, 0.079999999999999988, 0.89333333333333331, 0.13727506854649335, 0.94666666666666666, 0.11075498483890765, 0.86666666666666659, 0.30550504633038933]

##########################
Arquivos atuais: train(20)15.csv e test(20)15.csv
##########################
Iteração: 6
algUtl: 20
LR: 0.929004 (0.059761)
KNN: 0.899048 (0.103268)
DTC: 0.884762 (0.098064)
SVM: 0.929206 (0.074425)
RFC: 0.929206 (0.074425)
[0.92900432900432917, 0.059761169145450162, 0.8990476190476191, 0.10326784553475871, 0.88476190476190486, 0.098064411861652087, 0.92920634920634926, 0.074424642846553077, 0.92920634920634926, 0.074424642846553063]

##########################
Arquivos atuais: train(20)16.csv e test(20)16.csv
##########################
Iteração: 7
algUtl: 20
LR: 0.905000 (0.087787)
KNN: 0.897172 (0.120186)
DTC: 0.888997 (0.125510)
SVM: 0.915714 (0.073609)
RFC: 0.899711 (0.117505)
[0.90500000000000003, 0.087786567773671845, 

In [2]:
            rfc = RandomForestClassifier(random_state=12)

            from sklearn.model_selection import GridSearchCV

            param_grid = [{"criterion": ['gini', 'entropy'],"n_estimators": [10,25,30,35,40,45,50,100],
                           #"max_depth": [2,3,4,5,6,7],
                          "class_weight": ["balanced",None],
                          "min_samples_split": [2, 5, 10]}]

            score = 'f1'

            print("# Tunando hiperparâmetros para %s" % score)
            print()

            grid = GridSearchCV(rfc, param_grid, cv=5, scoring='%s_macro' % score)
            grid.fit(X_train, y_train)

            print("Melhor conjunto de hiperparâmetros encontrado:")
            print()
            print(grid.best_params_)
            # print()
            # print("Grade de valores encontrados:")
            # print()
            medias = grid.cv_results_['mean_test_score']
            desvios = grid.cv_results_['std_test_score']
            # for media, desvio, params in zip(medias, desvios, grid.cv_results_['params']):
            #     print("%0.3f (+/-%0.03f) for %r" % (media, desvio * 2, params))
            #     print()

            rfc = RandomForestClassifier(**grid.best_params_, random_state=500)

    #         rfc = RandomForestClassifier(parameters = grid.best_params_, random_state=12)

            kfold = KFold(n_splits=2, random_state=seed)
    
            try:
    
                kfold = StratifiedKFold(n_splits=10, random_state=seed) #Mudar para n-fold #Adicionado depois!
        
            except ValueError:
                
#                 kfold = StratifiedKFold(n_splits=5, random_state=seed) #Tirei pra ver se melhora
            
#             except ValueError:
                
                kfold = KFold(n_splits=10, random_state=seed)
            
#             except ValueError:
                
#                 kfold = KFold(n_splits=5, random_state=seed)
                
#             except ValueError:
                
#                 kfold = KFold(random_state=seed) #Default n_splits = 3
            
#             except ValueError:
                
#                 kfold = KFold(n_splits=2, random_state=seed)
            
            except:
                print('Erro com a geração dos folds!')
                print('Erro com o arquivo: ' + treino)
                exc_type, exc_obj, exc_tb = sys.exc_info()
                fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                print(exc_type, fname, exc_tb.tb_lineno)
                print(sys.exc_info())
                
            #Isso só serve para validar o uso do conjunto de treino 
            #Não influencia no resultado final
#             try:
#                 cv_results2 = model_selection.cross_val_score(rfc, X_train, y_train, cv=kfold, scoring='f1')
#                 msg = "%s com hiperparâmetros tunados: F1 = %f com desvio padrão = %f" % ('RFC', cv_results2.mean(), cv_results2.std())
#                 print(msg)
            
#             except:
#                 print("ERRO NA VALIDAÇÃO CRUZADA!")
#                 exc_type, exc_obj, exc_tb = sys.exc_info()
#                 fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
#                 print(exc_type, fname, exc_tb.tb_lineno)
#                 print(sys.exc_info())

                
            rfc.fit(X_train, y_train) #Treinando o modelo
            predicoes = rfc.predict(X_test) #Realizando a predição

    #         from sklearn.metrics import confusion_matrix
    #         matriz = confusion_matrix(y_test, predicoes)

    #         print(matriz)

            from sklearn.metrics import classification_report
            from sklearn.metrics import precision_recall_fscore_support

            # print(classification_report(y_test, predicoes))
    #         prec, rec, fbeta, supp = precision_recall_fscore_support(y_test, predicoes, average=None)
    #         print ('precision: %.5f' %(prec[1]))
    #         print ('recall: %.5f' %(rec[1]))
    #         print ('f1: %.5f' %(fbeta[1]))
    #         print ('non-matches: %d - matches: %d' %(supp[0], supp[1]))
    #         print('')

            # from sklearn.externals.six import StringIO  
            # from IPython.display import Image  
            # from sklearn.tree import export_graphviz
            # import pydotplus
            # dot_data = StringIO()
            # export_graphviz(rfc, out_file=dot_data,  
            #                 filled=True, rounded=True,
            #                 special_characters=True, feature_names=X.columns)
            # graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
            # Image(graph.create_png())

            predicoes = rfc.predict(XtoClass)

            from sklearn.metrics import confusion_matrix
            matriz = confusion_matrix(ytoClass, predicoes)
            print(matriz)

            this_tn, this_fp, this_fn, this_tp = 0, 0, 0, 0

            this_tn, this_fp, this_fn, this_tp = confusion_matrix(ytoClass, predicoes).ravel()
            print('tn, fp, fn, tp')
            print(this_tn, this_fp, this_fn, this_tp)



            from sklearn.metrics import classification_report
            from sklearn.metrics import precision_recall_fscore_support

            # print(classification_report(y_test, predicoes))
    #         prec, rec, fbeta, supp = precision_recall_fscore_support(ytoClass, predicoes, average=None)
    #         print ('precision: %.5f' %(prec[1]))
    #         print ('recall: %.5f' %(rec[1]))
    #         print ('f1: %.5f' %(fbeta[1]))
    #         print ('non-matches: %d - matches: %d' %(supp[0], supp[1]))
    #         print('')


            ########################

            #Atualizar as estatísticas
            abordagem = 'DS'
            #print 'abordagem é %s' %(abordagem)

            #algUtl = linhaAtual['algoritmosUtilizados'].item()
            iteracao = 2
            inspecoesManuais = linhaAtual['inspecoesManuais'].item()
            da = linhaAtual['da'].item() + (this_tp + this_fp) #Adiciona todos os casos positivos identificados
            dm = linhaAtual['dm'].item()             #na predição
            ndm = linhaAtual['ndm'].item()


            fn = float(linhaAtual['fn'].item() - this_tp ) #Não tenho certeza se é isso
            tp = this_tp + float(linhaAtual['tp'].item()) #+ dm) #Recuperar de toClass
            print('tp é igual a: %d' %(tp))

            fp = this_fp + float(linhaAtual['fp'].item())
            #tn = tn + float(linhaAtual['tn'].item() - tp) #+ ndm) #Recuperar de toClass
            tn = (9762 * 9763) / 2 -(tp+fp+fn)



            precision = tp/(tp+fp)
            recall = tp/(tp+fn)
            fmeasure = 2*((precision*recall)/(precision+recall))

            #Adicionando valor à última linha
    #         estatisticas.loc[(etapa, permutacao), ['abordagem', 'algoritmosUtilizados', 'iteracao', 'inspecoesManuais',
    #            'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp',
    #            'fp', 'tn', 'fn'] ] = ([abordagem, algUtl, iteracao, inspecoesManuais,
    #            precision, recall, fmeasure, da, dm, ndm, tp, fp, tn, fn])
            estatisticas.loc[(algUtl, permutacao, etapa), ['abordagem', 'iteracao', 'inspecoesManuais',
                'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp',
                'fp', 'tn', 'fn'] ] = ([abordagem, iteracao, inspecoesManuais,
                precision, recall, fmeasure, da, dm, ndm, tp, fp, tn, fn])

            #'''

    # estatisticas = estatisticas.reset_index(level=['etapa', 'permutacao'])
    estatisticas = estatisticas.reset_index(level=['algoritmosUtilizados', 'permutacao', 'etapa'])
    # estatisticas.head()                   
    #                    

    estatisticas = estatisticas[['abordagem', 'etapa', 'algoritmosUtilizados', 'permutacao', 'iteracao', 'inspecoesManuais', 'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']]

    estatisticas[['algoritmosUtilizados', 'iteracao', 'inspecoesManuais', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']] = \
    estatisticas[['algoritmosUtilizados', 'iteracao', 'inspecoesManuais', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']].astype(int)

    dirEst = "../csv/"
    # dirEst = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/"
    # dirEst = "../arqResult/csv/"


    estatisticas.to_csv(dirEst+'estatisticaInicialDS3-k'+str(k)+'.csv', sep=';', index=False)        

../csv/conjuntosDS/treinoTeste-k3/
10

##########################
Arquivos atuais: train(10)10.csv e test(10)10.csv
##########################
Iteração: 1
algUtl: 10
# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 50}
[[351  14]
 [  4 152]]
tn, fp, fn, tp
351 14 4 152
tp é igual a: 251

##########################
Arquivos atuais: train(10)11.csv e test(10)11.csv
##########################
Iteração: 2
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
[[758  27]
 [  7 106]]
tn, fp, fn, tp
758 27 7 106
tp é igual a: 257

##########################
Arquivos atuais: train(10)12.csv e test(10)12.csv
##########################
Iteração: 3
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
[[517   9]
 [  8 158]]
tn, fp, fn, tp
517 9 8 158
tp é igual a: 256

##########################
Arquivos atuais: train(10)13.csv e test(10)13.csv
##########################
Iteração: 4
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 10}
[[351  10]
 [  9 147]]
tn, fp, fn, tp
351 10 9 147
tp é igual a: 241

##########################
Arquivos atuais: train(10)14.csv e test(10)14.csv
##########################
Iteração: 5
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
[[460   9]
 [  9 158]]
tn, fp, fn, tp
460 9 9 158
tp é igual a: 247

##########################
Arquivos atuais: train(10)15.csv e test(10)15.csv
##########################
Iteração: 6
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 35}
[[393   8]
 [  3 179]]
tn, fp, fn, tp
393 8 3 179
tp é igual a: 251

##########################
Arquivos atuais: train(10)16.csv e test(10)16.csv
##########################
Iteração: 7
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[  0  35]
 [  0 154]]
tn, fp, fn, tp
0 35 0 154
tp é igual a: 248

##########################
Arquivos atuais: train(10)17.csv e test(10)17.csv
##########################
Iteração: 8
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 30}
[[223  13]
 [ 10 165]]
tn, fp, fn, tp
223 13 10 165
tp é igual a: 252

##########################
Arquivos atuais: train(10)18.csv e test(10)18.csv
##########################
Iteração: 9
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.p

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[ 17 506]
 [  4 166]]
tn, fp, fn, tp
17 506 4 166
tp é igual a: 260

##########################
Arquivos atuais: train(10)19.csv e test(10)19.csv
##########################
Iteração: 10
algUtl: 10
# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[341  10]
 [ 14 159]]
tn, fp, fn, tp
341 10 14 159
tp é igual a: 230

##########################
Arquivos atuais: train(10)20.csv e test(10)20.csv
##########################
Iteração: 11
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'gini', 'min_samples_split': 10, 'n_estimators': 35}
[[637  10]
 [  4 131]]
tn, fp, fn, tp
637 10 4 131
tp é igual a: 251
15

##########################
Arquivos atuais: train(15)10.csv e test(15)10.csv
##########################
Iteração: 1
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[706  11]
 [  9 181]]
tn, fp, fn, tp
706 11 9 181
tp é igual a: 248

##########################
Arquivos atuais: train(15)11.csv e test(15)11.csv
##########################
Iteração: 2
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[138  12]
 [ 23 139]]
tn, fp, fn, tp
138 12 23 139
tp é igual a: 238

##########################
Arquivos atuais: train(15)12.csv e test(15)12.csv
##########################
Iteração: 3
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[800  13]
 [ 15 170]]
tn, fp, fn, tp
800 13 15 170
tp é igual a: 250

##########################
Arquivos atuais: train(15)13.csv e test(15)13.csv
##########################
Iteração: 4
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 45}
[[534  11]
 [ 13 183]]
tn, fp, fn, tp
534 11 13 183
tp é igual a: 252

##########################
Arquivos atuais: train(15)14.csv e test(15)14.csv
##########################
Iteração: 5
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
[[433  10]
 [  6 180]]
tn, fp, fn, tp
433 10 6 180
tp é igual a: 251

##########################
Arquivos atuais: train(15)15.csv e test(15)15.csv
##########################
Iteração: 6
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 10}
[[749  14]
 [  8 176]]
tn, fp, fn, tp
749 14 8 176
tp é igual a: 256

##########################
Arquivos atuais: train(15)16.csv e test(15)16.csv
##########################
Iteração: 7
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[636  10]
 [ 25 132]]
tn, fp, fn, tp
636 10 25 132
tp é igual a: 233

##########################
Arquivos atuais: train(15)17.csv e test(15)17.csv
##########################
Iteração: 8
algUtl: 15


C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
[[470  12]
 [ 10 178]]
tn, fp, fn, tp
470 12 10 178
tp é igual a: 249

##########################
Arquivos atuais: train(15)18.csv e test(15)18.csv
##########################
Iteração: 9
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 100}
[[687  11]
 [  9 153]]
tn, fp, fn, tp
687 11 9 153
tp é igual a: 249

##########################
Arquivos atuais: train(15)19.csv e test(15)19.csv
##########################
Iteração: 10
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'entropy', 'min_samples_split': 10, 'n_estimators': 100}
[[802   8]
 [ 17 167]]
tn, fp, fn, tp
802 8 17 167
tp é igual a: 247

##########################
Arquivos atuais: train(15)20.csv e test(15)20.csv
##########################
Iteração: 11
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[803   8]
 [ 12 166]]
tn, fp, fn, tp
803 8 12 166
tp é igual a: 253
20

##########################
Arquivos atuais: train(20)10.csv e test(20)10.csv
##########################
Iteração: 1
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
[[802  15]
 [ 13 175]]
tn, fp, fn, tp
802 15 13 175
tp é igual a: 253

##########################
Arquivos atuais: train(20)11.csv e test(20)11.csv
##########################
Iteração: 2
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[814  13]
 [ 14 172]]
tn, fp, fn, tp
814 13 14 172
tp é igual a: 251

##########################
Arquivos atuais: train(20)12.csv e test(20)12.csv
##########################
Iteração: 3
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
[[680  15]
 [  8 171]]
tn, fp, fn, tp
680 15 8 171
tp é igual a: 250

##########################
Arquivos atuais: train(20)13.csv e test(20)13.csv
##########################
Iteração: 4
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
[[774  18]
 [  4 173]]
tn, fp, fn, tp
774 18 4 173
tp é igual a: 261

##########################
Arquivos atuais: train(20)14.csv e test(20)14.csv
##########################
Iteração: 5
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[829  13]
 [ 21 169]]
tn, fp, fn, tp
829 13 21 169
tp é igual a: 245

##########################
Arquivos atuais: train(20)15.csv e test(20)15.csv
##########################
Iteração: 6
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
[[799  17]
 [ 12 182]]
tn, fp, fn, tp
799 17 12 182
tp é igual a: 254

##########################
Arquivos atuais: train(20)16.csv e test(20)16.csv
##########################
Iteração: 7
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 35}
[[747  19]
 [ 11 174]]
tn, fp, fn, tp
747 19 11 174
tp é igual a: 254

##########################
Arquivos atuais: train(20)17.csv e test(20)17.csv
##########################
Iteração: 8
algUtl: 20


C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
[[588  13]
 [ 16 177]]
tn, fp, fn, tp
588 13 16 177
tp é igual a: 250

##########################
Arquivos atuais: train(20)18.csv e test(20)18.csv
##########################
Iteração: 9
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[685   9]
 [ 23 154]]
tn, fp, fn, tp
685 9 23 154
tp é igual a: 235

##########################
Arquivos atuais: train(20)19.csv e test(20)19.csv
##########################
Iteração: 10
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
[[705  12]
 [ 12 172]]
tn, fp, fn, tp
705 12 12 172
tp é igual a: 247

##########################
Arquivos atuais: train(20)20.csv e test(20)20.csv
##########################
Iteração: 11
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 25}
[[816  11]
 [ 20 167]]
tn, fp, fn, tp
816 11 20 167
tp é igual a: 245


C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
