In [2]:
import numpy as np
import math
import pandas as pd
import matplotlib
%matplotlib inline

import os
import glob
import re

# janelas = [2,3,4,5]
janelas = [3]

for k in janelas:

    abordagemAA = '2 - AA[dg-arj]' #'2 - AA[pet-chr]' ou '2 - AA[dg-arj]'
    dirOrig = "../csv/conjuntosDS/treinoTeste-k"+str(k)+"/"
    # dirOrig = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/conjuntosDS/treinoTeste/"
    # dirOrig = "../arqResult/csv/conjuntosDS/conjuntosDiverg/treinoTeste/"
    # estat = "../csv/estatisticaInicialDS2.csv"
    estat = "../csv/estatisticaInicialDS2-DgArj-k"+str(k)+".csv"
    # estat = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/estatisticaInicialDS2.csv"
    # estat = "../arqResult/csv/estatisticaInicialDS2.csv"

    etapa = '3 - clasf'

    # estatisticas = pd.read_csv(estat, index_col=['etapa','permutacao'], sep=';')
    estatisticas = pd.read_csv(estat, index_col=['algoritmosUtilizados','permutacao','etapa'], sep=';')
#     estatisticas.tail()

    arquivos = os.listdir(dirOrig)
    # print(arquivos)
    #print(len(arquivos))

    train = []
    test = []

    for arq in arquivos:
        if arq.startswith("train"):
            train.append(arq)
        elif arq.startswith("test"):
            test.append(arq)

    # print('tamanho de train: %d' %(len(train)))        

    # print('tamanho de test: %d' %(len(test)))

    # print (train)    
    # print (test)    



    #lista = ['10', '15', '20', '25'] #Assumindo que serão esses os conjuntos de algoritmos
    lista = ['10', '15', '20'] #Assumindo que serão esses os conjuntos de algoritmos
#     lista = ['10'] #Assumindo que serão esses os conjuntos de algoritmos
    # lista = ['3'] #Assumindo que serão esses os conjuntos de algoritmos

    for i in lista: 

        cont = 0

        trainAtual = []
        testAtual = []

        for arq in train:
            if '('+i+')' in arq:
#             if 'train(10)141' in arq:    
                trainAtual.append(arq)
        for arq in test:
            if '('+i+')' in arq:
#             if 'test(10)141' in arq:
                testAtual.append(arq)

    #     print('lista desordenada')
    #     print(trainAtual)

    #     print('tamanho antes: %d' %(len(trainAtual)))

        #Ordenando a lista
        trainAtual = sorted(trainAtual)
        testAtual = sorted(testAtual)

    #     for x in trainAtual:
    #         print(x)



    # #     print('lista ordenada')
    # #     print(trainAtual)

    #     print('tamanho depois: %d' %(len(trainAtual)))

    #     print(type(trainAtual))


        print (i)

    #     print(trainAtual)
    #     print(testAtual)

        tam = len(trainAtual) #Mesma coisa para testAtual

        for pos in range(tam):
    #         print(pos)
            print('Arquivos atuais: %s e %s' %(trainAtual[pos], testAtual[pos]))

            treino = dirOrig+trainAtual[pos]
            teste = dirOrig+testAtual[pos]

    #         print('treino: %s' %(treino))

    #         tp, fp, tn, fn = 0

            num = trainAtual[pos].replace('train('+i+')','')
            num = num.replace('.csv','')

            cont += 1

            print('Iteração: %d' %(cont))

    #         print('num: %s' %(num))

            algUtl = re.sub('train.*\(', r'', trainAtual[pos]) #Alterar para fazer a substituição de tudo em uma linha só
            algUtl = re.sub('\).*', r'', algUtl) #Alterar para fazer a substituição de tudo em uma linha só
            algUtl = int(algUtl)


            print('algUtl: %d' %(algUtl))

            permutacao = int(num)
    #         linhaAtual = estatisticas.loc[('2 - AA[pet-chr]', permutacao), : ] #Armazena a linha correspondente à permutação
    #         linhaAtual = estatisticas.loc[('1 - acm diverg', permutacao), : ] #Armazena a linha correspondente à permutação
            linhaAtual = estatisticas.loc[algUtl, permutacao, abordagemAA, : ] #Armazena a linha correspondente à permutação
#             print (linhaAtual)
#             print(linhaAtual.columns)

        #'''
    #         all = pd.read_csv("train.csv", index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)
    #         toClass = pd.read_csv("test.csv", index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)

    #         all = pd.read_csv(treino, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)
    #         toClass = pd.read_csv(teste, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'duplicata'), header = None)

            all = pd.read_csv(treino, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'track10', 'track11', 'duplicata'), header = 0) #Era header = None
            toClass = pd.read_csv(teste, index_col=False, sep=';', names=('title', 'artist', 'track01', 'track02', 'track03', 'track10', 'track11', 'duplicata'), header = 0) #Era header = None


            # all['artist-title'] = all['artist'] * all['title']
            # cols = list(all.columns.values)
            # cols.pop(cols.index('duplicata'))
            # all = all[cols+['duplicata']]

            #Pesos baseados no Alg17

            all['artist-title'] = all['artist'] * all['title']
            all['soma-pesos'] = (all['artist']*1 + all['title']*2 + all['track01']*0.8 + all['track02']*0.8)/4.6
            cols = list(all.columns.values)
            cols.pop(cols.index('duplicata'))
            all = all[cols+['duplicata']]

            # toClass['artist-title'] = toClass['artist'] * toClass['title']
            # cols = list(toClass.columns.values)
            # cols.pop(cols.index('duplicata'))
            # toClass = toClass[cols+['duplicata']]

            #Pesos baseados no Alg17

            toClass['artist-title'] = toClass['artist'] * toClass['title']
            toClass['soma-pesos'] = (toClass['artist']*1 + toClass['title']*2 + toClass['track01']*0.8 + toClass['track02']*0.8)/4.6
            cols = list(toClass.columns.values)
            cols.pop(cols.index('duplicata'))
            toClass = toClass[cols+['duplicata']]

            #Separação do conjunto X do conjunto y
            # X = all.loc[:,'title':'artist-title']
            X = all.loc[:,'title':'soma-pesos']
            y = all.duplicata

            # XtoClass = toClass.loc[:,'title':'artist-title']
            XtoClass = toClass.loc[:,'title':'soma-pesos']
            ytoClass = toClass.duplicata

            from sklearn import model_selection

            X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.20, random_state=2)

            from sklearn.ensemble import RandomForestClassifier
            from sklearn.model_selection import StratifiedKFold
            from sklearn.model_selection import KFold
            from sklearn import model_selection

            seed = 500

            '''

            from sklearn.linear_model import LogisticRegression
            from sklearn.tree import DecisionTreeClassifier
            from sklearn.neighbors import KNeighborsClassifier
            from sklearn.svm import SVC

            modelos = []
            modelos.append(('LR', LogisticRegression()))
            modelos.append(('KNN', KNeighborsClassifier()))
            modelos.append(('DTC', DecisionTreeClassifier()))
            modelos.append(('SVM', SVC()))
            modelos.append(('RF', RandomForestClassifier()))



            # Avaliação de cada modelo por vez
            resultados = []
            nomes = []
            for nome, modelo in modelos:
                kfold = StratifiedKFold(n_splits=10, random_state=seed) #Mudar para n-fold
                cv_results = model_selection.cross_val_score(modelo, X_train, y_train, cv=kfold, scoring='f1')
                msg = "%s: %f (%f)" % (nome, cv_results.mean(), cv_results.std()) #Iprimir em um arquivo
                print(msg)
            '''

            dtc = RandomForestClassifier(random_state=12)

            from sklearn.model_selection import GridSearchCV

            param_grid = [{"criterion": ['gini', 'entropy'],"n_estimators": [10,25,30,35,40,45,50,100],
                           #"max_depth": [2,3,4,5,6,7],
                          "class_weight": ["balanced",None],
                          "min_samples_split": [2, 5, 10]}]

            score = 'f1'

            print("# Tunando hiperparâmetros para %s" % score)
            print()

            grid = GridSearchCV(dtc, param_grid, cv=5, scoring='%s_macro' % score)
            grid.fit(X_train, y_train)

            print("Melhor conjunto de hiperparâmetros encontrado:")
            print()
            print(grid.best_params_)
            # print()
            # print("Grade de valores encontrados:")
            # print()
            medias = grid.cv_results_['mean_test_score']
            desvios = grid.cv_results_['std_test_score']
            # for media, desvio, params in zip(medias, desvios, grid.cv_results_['params']):
            #     print("%0.3f (+/-%0.03f) for %r" % (media, desvio * 2, params))
            #     print()

            rfc = RandomForestClassifier(**grid.best_params_, random_state=500)

    #         rfc = RandomForestClassifier(parameters = grid.best_params_, random_state=12)

            kfold = KFold(n_splits=10, random_state=seed)
    
            try:
    
                kfold = StratifiedKFold(n_splits=10, random_state=seed) #Mudar para n-fold #Adicionado depois!
        
            except ValueError:
                
                kfold = KFold(n_splits=10, random_state=seed)
            
            except:
                print('Erro com o arquivo: ' + treino)
                

            cv_results2 = model_selection.cross_val_score(rfc, X_train, y_train, cv=kfold, scoring='f1')
            msg = "%s com hiperparâmetros tunados: F1 = %f com desvio padrão = %f" % ('DTC', cv_results2.mean(), cv_results2.std())
            print(msg)

            rfc.fit(X_train, y_train)
            predicoes = rfc.predict(X_test)

    #         from sklearn.metrics import confusion_matrix
    #         matriz = confusion_matrix(y_test, predicoes)

    #         print(matriz)

            from sklearn.metrics import classification_report
            from sklearn.metrics import precision_recall_fscore_support

            # print(classification_report(y_test, predicoes))
    #         prec, rec, fbeta, supp = precision_recall_fscore_support(y_test, predicoes, average=None)
    #         print ('precision: %.5f' %(prec[1]))
    #         print ('recall: %.5f' %(rec[1]))
    #         print ('f1: %.5f' %(fbeta[1]))
    #         print ('non-matches: %d - matches: %d' %(supp[0], supp[1]))
    #         print('')

            # from sklearn.externals.six import StringIO  
            # from IPython.display import Image  
            # from sklearn.tree import export_graphviz
            # import pydotplus
            # dot_data = StringIO()
            # export_graphviz(rfc, out_file=dot_data,  
            #                 filled=True, rounded=True,
            #                 special_characters=True, feature_names=X.columns)
            # graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
            # Image(graph.create_png())

            predicoes = rfc.predict(XtoClass)

            from sklearn.metrics import confusion_matrix
            matriz = confusion_matrix(ytoClass, predicoes)
            print(matriz)

            this_tn, this_fp, this_fn, this_tp = 0, 0, 0, 0

            this_tn, this_fp, this_fn, this_tp = confusion_matrix(ytoClass, predicoes).ravel()
            print('tn, fp, fn, tp')
            print(this_tn, this_fp, this_fn, this_tp)



            from sklearn.metrics import classification_report
            from sklearn.metrics import precision_recall_fscore_support

            # print(classification_report(y_test, predicoes))
    #         prec, rec, fbeta, supp = precision_recall_fscore_support(ytoClass, predicoes, average=None)
    #         print ('precision: %.5f' %(prec[1]))
    #         print ('recall: %.5f' %(rec[1]))
    #         print ('f1: %.5f' %(fbeta[1]))
    #         print ('non-matches: %d - matches: %d' %(supp[0], supp[1]))
    #         print('')


            ########################

            #Atualizar as estatísticas
            abordagem = 'DS'
            #print 'abordagem é %s' %(abordagem)

            #algUtl = linhaAtual['algoritmosUtilizados'].item()
            iteracao = 2
            inspecoesManuais = linhaAtual['inspecoesManuais'].item()
            da = linhaAtual['da'].item() + (this_tp + this_fp) #Adiciona todos os casos positivos identificados
            dm = linhaAtual['dm'].item()             #na predição
            ndm = linhaAtual['ndm'].item()


            fn = float(linhaAtual['fn'].item() - this_tp ) #Não tenho certeza se é isso
            tp = this_tp + float(linhaAtual['tp'].item()) #+ dm) #Recuperar de toClass
            print('tp é igual a: %d' %(tp))

            fp = this_fp + float(linhaAtual['fp'].item())
            #tn = tn + float(linhaAtual['tn'].item() - tp) #+ ndm) #Recuperar de toClass
            tn = (9762 * 9763) / 2 -(tp+fp+fn)



            precision = tp/(tp+fp)
            recall = tp/(tp+fn)
            fmeasure = 2*((precision*recall)/(precision+recall))

            #Adicionando valor à última linha
    #         estatisticas.loc[(etapa, permutacao), ['abordagem', 'algoritmosUtilizados', 'iteracao', 'inspecoesManuais',
    #            'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp',
    #            'fp', 'tn', 'fn'] ] = ([abordagem, algUtl, iteracao, inspecoesManuais,
    #            precision, recall, fmeasure, da, dm, ndm, tp, fp, tn, fn])
            estatisticas.loc[(algUtl, permutacao, etapa), ['abordagem', 'iteracao', 'inspecoesManuais',
                'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp',
                'fp', 'tn', 'fn'] ] = ([abordagem, iteracao, inspecoesManuais,
                precision, recall, fmeasure, da, dm, ndm, tp, fp, tn, fn])

            #'''

    # estatisticas = estatisticas.reset_index(level=['etapa', 'permutacao'])
    estatisticas = estatisticas.reset_index(level=['algoritmosUtilizados', 'permutacao', 'etapa'])
    # estatisticas.head()                   
    #                    

    estatisticas = estatisticas[['abordagem', 'etapa', 'algoritmosUtilizados', 'permutacao', 'iteracao', 'inspecoesManuais', 'precision', 'recall', 'f-measure', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']]

    estatisticas[['algoritmosUtilizados', 'iteracao', 'inspecoesManuais', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']] = \
    estatisticas[['algoritmosUtilizados', 'iteracao', 'inspecoesManuais', 'da', 'dm', 'ndm', 'tp', 'fp', 'tn', 'fn']].astype(int)

    dirEst = "../csv/"
    # dirEst = "c:/Users/Diego/Documents/NetBeansProjects/Master-SKYAM/AS/src/csv/"
    # dirEst = "../arqResult/csv/"


    estatisticas.to_csv(dirEst+'estatisticaInicialDS3-k'+str(k)+'.csv', sep=';', index=False)        

10
Arquivos atuais: train(10)10.csv e test(10)10.csv
Iteração: 1
algUtl: 10
# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 10, 'n_estimators': 40}
DTC com hiperparâmetros tunados: F1 = 0.907020 com desvio padrão = 0.087625
[[343   8]
 [  5 120]]
tn, fp, fn, tp
343 8 5 120
tp é igual a: 251
Arquivos atuais: train(10)11.csv e test(10)11.csv
Iteração: 2
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 10, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.971429 com desvio padrão = 0.057143
[[728  48]
 [ 12  81]]
tn, fp, fn, tp
728 48 12 81
tp é igual a: 252
Arquivos atuais: train(10)12.csv e test(10)12.csv
Iteração: 3
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'gini', 'min_samples_split': 10, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.957143 com desvio padrão = 0.065465
[[516  28]
 [  4 156]]
tn, fp, fn, tp
516 28 4 156
tp é igual a: 262
Arquivos atuais: train(10)13.csv e test(10)13.csv
Iteração: 4
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is 

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 10, 'n_estimators': 30}


C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 8 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


DTC com hiperparâmetros tunados: F1 = 0.909524 com desvio padrão = 0.105302
[[362  14]
 [ 11 138]]
tn, fp, fn, tp
362 14 11 138
tp é igual a: 242
Arquivos atuais: train(10)14.csv e test(10)14.csv
Iteração: 5
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.963492 com desvio padrão = 0.056366
[[444  27]
 [  7 138]]
tn, fp, fn, tp
444 27 7 138
tp é igual a: 250
Arquivos atuais: train(10)15.csv e test(10)15.csv
Iteração: 6
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is 

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 50}
DTC com hiperparâmetros tunados: F1 = 0.985714 com desvio padrão = 0.042857
[[257 166]
 [ 10 160]]
tn, fp, fn, tp
257 166 10 160
tp é igual a: 248
Arquivos atuais: train(10)16.csv e test(10)16.csv
Iteração: 7
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.p

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.985714 com desvio padrão = 0.042857
[[ 14  22]
 [  3 139]]
tn, fp, fn, tp
14 22 3 139
tp é igual a: 245
Arquivos atuais: train(10)17.csv e test(10)17.csv
Iteração: 8
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is 

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}


C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 7 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


DTC com hiperparâmetros tunados: F1 = 0.940000 com desvio padrão = 0.091652
[[209  37]
 [  4 161]]
tn, fp, fn, tp
209 37 4 161
tp é igual a: 260
Arquivos atuais: train(10)18.csv e test(10)18.csv
Iteração: 9
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.p

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: Und

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: Und

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: Und

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\metrics\c

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 30}


C:\Users\Diego\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


DTC com hiperparâmetros tunados: F1 = 0.931429 com desvio padrão = 0.085905
[[346 174]
 [ 11 148]]
tn, fp, fn, tp
346 174 11 148
tp é igual a: 254
Arquivos atuais: train(10)19.csv e test(10)19.csv
Iteração: 10
algUtl: 10
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 100}
DTC com hiperparâmetros tunados: F1 = 0.918095 com desvio padrão = 0.111733
[[337   8]
 [ 17 144]]
tn, fp, fn, tp
337 8 17 144
tp é igual a: 229


C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Arquivos atuais: train(10)20.csv e test(10)20.csv
Iteração: 11
algUtl: 10
# Tunando hiperparâmetros para f1

Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.988889 com desvio padrão = 0.033333
[[635  12]
 [  9 101]]
tn, fp, fn, tp
635 12 9 101
tp é igual a: 246
15
Arquivos atuais: train(15)10.csv e test(15)10.csv
Iteração: 1
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 40}
DTC com hiperparâmetros tunados: F1 = 0.931623 com desvio padrão = 0.091880
[[678  27]
 [  8 157]]
tn, fp, fn, tp
678 27 8 157
tp é igual a: 250
Arquivos atuais: train(15)11.csv e test(15)11.csv
Iteração: 2
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.940793 com desvio padrão = 0.099248
[[111  21]
 [  8 119]]
tn, fp, fn, tp
111 21 8 119
tp é igual a: 253
Arquivos atuais: train(15)12.csv e test(15)12.csv
Iteração: 3
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.943687 com desvio padrão = 0.079840
[[762  37]
 [  3 155]]
tn, fp, fn, tp
762 37 3 155
tp é igual a: 262
Arquivos atuais: train(15)13.csv e test(15)13.csv
Iteração: 4
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.945152 com desvio padrão = 0.073636
[[526   8]
 [ 11 141]]
tn, fp, fn, tp
526 8 11 141
tp é igual a: 256
Arquivos atuais: train(15)14.csv e test(15)14.csv
Iteração: 5
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.946667 com desvio padrão = 0.110755
[[446  14]
 [ 21 168]]
tn, fp, fn, tp
446 14 21 168
tp é igual a: 238
Arquivos atuais: train(15)15.csv e test(15)15.csv
Iteração: 6
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.940793 com desvio padrão = 0.049425
[[723  11]
 [  5 141]]
tn, fp, fn, tp
723 11 5 141
tp é igual a: 259
Arquivos atuais: train(15)16.csv e test(15)16.csv
Iteração: 7
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 35}
DTC com hiperparâmetros tunados: F1 = 0.913015 com desvio padrão = 0.048931
[[615  13]
 [  8 116]]
tn, fp, fn, tp
615 13 8 116
tp é igual a: 250
Arquivos atuais: train(15)17.csv e test(15)17.csv
Iteração: 8
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.933333 com desvio padrão = 0.133333
[[449  51]
 [  4 186]]
tn, fp, fn, tp
449 51 4 186
tp é igual a: 257
Arquivos atuais: train(15)18.csv e test(15)18.csv
Iteração: 9
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 10, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.952525 com desvio padrão = 0.047817
[[660   5]
 [ 23 115]]
tn, fp, fn, tp
660 5 23 115
tp é igual a: 236
Arquivos atuais: train(15)19.csv e test(15)19.csv
Iteração: 10
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.960000 com desvio padrão = 0.080000
[[803   9]
 [ 18 162]]
tn, fp, fn, tp
803 9 18 162
tp é igual a: 248
Arquivos atuais: train(15)20.csv e test(15)20.csv
Iteração: 11
algUtl: 15
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.932381 com desvio padrão = 0.112159
[[799   8]
 [ 18 152]]
tn, fp, fn, tp
799 8 18 152
tp é igual a: 250
20
Arquivos atuais: train(20)10.csv e test(20)10.csv
Iteração: 1
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 30}
DTC com hiperparâmetros tunados: F1 = 0.959840 com desvio padrão = 0.051697
[[769  18]
 [  3 142]]
tn, fp, fn, tp
769 18 3 142
tp é igual a: 264
Arquivos atuais: train(20)11.csv e test(20)11.csv
Iteração: 2
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.977778 com desvio padrão = 0.044444
[[801  18]
 [  4 166]]
tn, fp, fn, tp
801 18 4 166
tp é igual a: 263
Arquivos atuais: train(20)12.csv e test(20)12.csv
Iteração: 3
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 5, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.944833 com desvio padrão = 0.045702
[[659  12]
 [ 11 142]]
tn, fp, fn, tp
659 12 11 142
tp é igual a: 250
Arquivos atuais: train(20)13.csv e test(20)13.csv
Iteração: 4
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.970707 com desvio padrão = 0.045049
[[760  14]
 [ 10 141]]
tn, fp, fn, tp
760 14 10 141
tp é igual a: 257
Arquivos atuais: train(20)14.csv e test(20)14.csv
Iteração: 5
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 2, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.974603 com desvio padrão = 0.051287
[[800  16]
 [  9 158]]
tn, fp, fn, tp
800 16 9 158
tp é igual a: 257
Arquivos atuais: train(20)15.csv e test(20)15.csv
Iteração: 6
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'entropy', 'min_samples_split': 2, 'n_estimators': 50}
DTC com hiperparâmetros tunados: F1 = 0.916061 com desvio padrão = 0.078812
[[782  14]
 [ 10 145]]
tn, fp, fn, tp
782 14 10 145
tp é igual a: 256
Arquivos atuais: train(20)16.csv e test(20)16.csv
Iteração: 7
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': None, 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 30}
DTC com hiperparâmetros tunados: F1 = 0.916519 com desvio padrão = 0.054112
[[721  15]
 [  5 141]]
tn, fp, fn, tp
721 15 5 141
tp é igual a: 260
Arquivos atuais: train(20)17.csv e test(20)17.csv
Iteração: 8
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.953663 com desvio padrão = 0.062088
[[563  13]
 [  7 146]]
tn, fp, fn, tp
563 13 7 146
tp é igual a: 259
Arquivos atuais: train(20)18.csv e test(20)18.csv
Iteração: 9
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 2, 'n_estimators': 40}
DTC com hiperparâmetros tunados: F1 = 0.945714 com desvio padrão = 0.084225
[[677  14]
 [  9 167]]
tn, fp, fn, tp
677 14 9 167
tp é igual a: 252
Arquivos atuais: train(20)19.csv e test(20)19.csv
Iteração: 10
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 5, 'n_estimators': 10}
DTC com hiperparâmetros tunados: F1 = 0.965714 com desvio padrão = 0.069752
[[698  12]
 [ 12 167]]
tn, fp, fn, tp
698 12 12 167
tp é igual a: 249
Arquivos atuais: train(20)20.csv e test(20)20.csv
Iteração: 11
algUtl: 20
# Tunando hiperparâmetros para f1



C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)


Melhor conjunto de hiperparâmetros encontrado:

{'class_weight': 'balanced', 'criterion': 'gini', 'min_samples_split': 10, 'n_estimators': 25}
DTC com hiperparâmetros tunados: F1 = 0.977778 com desvio padrão = 0.044444
[[798  15]
 [  9 158]]
tn, fp, fn, tp
798 15 9 158
tp é igual a: 258


C:\Users\Diego\Anaconda3\lib\site-packages\ipykernel\kernelbase.py:399: PerformanceWarning: indexing past lexsort depth may impact performance.
  user_expressions, allow_stdin)
